// <auto-generated />
using System;
using Api_Prueba;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APi_prueba.Migrations
{
    [DbContext(typeof(ApplicationDbcontex))]
    [Migration("20240626033729_primerabasedatos")]
    partial class primerabasedatos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("Api_Prueba.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int>("Peso")
                        .HasColumnType("INTEGER");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("f83bc361-e443-47f7-89ec-556241277222"),
                            Nombre = "Actividades pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("f83bc361-e443-47f7-89ec-556241277233"),
                            Nombre = "Actividades personales",
                            Peso = 69
                        });
                });

            modelBuilder.Entity("Api_Prueba.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("TEXT");

                    b.Property<int>("Prioridad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("f83bc361-e443-47f7-89ec-556241277234"),
                            CategoriaId = new Guid("f83bc361-e443-47f7-89ec-556241277222"),
                            FechaCreacion = new DateTime(2024, 6, 25, 23, 37, 27, 263, DateTimeKind.Local).AddTicks(328),
                            Prioridad = 1,
                            Titulo = "Pago de servicios publicos"
                        },
                        new
                        {
                            TareaId = new Guid("f83bc361-e443-47f7-89ec-556241277235"),
                            CategoriaId = new Guid("f83bc361-e443-47f7-89ec-556241277233"),
                            FechaCreacion = new DateTime(2024, 6, 25, 23, 37, 27, 263, DateTimeKind.Local).AddTicks(349),
                            Prioridad = 0,
                            Titulo = "Terminar pelicula"
                        });
                });

            modelBuilder.Entity("Api_Prueba.Models.Tarea", b =>
                {
                    b.HasOne("Api_Prueba.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Api_Prueba.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
